name: kdlfmt
on:
  - push
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup-kdlfmt
        uses: hougesen/kdlfmt@v0.1.0

      - name: Run kdlfmt
        run: kdlfmt check .
